// import { ClerkProvider } from "@clerk/nextjs";
// import '../globals.css';
// import { Inter } from "next/font/google";

// export const metadata = {
//     title: "Idealy",
//     description: "",
// };

// const inter = Inter({subsets: ["latin"]});

// export default function RootLayout({children}: {children: React.ReactNode}) {
//     return(
//         <ClerkProvider>
//             <html lang="en">
//                 <body className={`${inter.className} bg-dark-1`}>
//                     {children}
//                 </body>
//             </html>
//         </ClerkProvider>
//     )
// }


import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang='en'>
        <body className={`${inter.className} bg-light-1`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}